os:
  - linux

language: node_js

node_js:
  - '10.8.0'

script: ./scripts/travis-build.sh

branches:
  only:
    - 160145646-continouos-integration-badges

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change